name: Docker Image CI

on:
  push:
    tags:
    - 'v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'

env:
  IMAGE_NAME: my-app
  # DOCKERFILE_PATH: ./Dockerfile
  # DOCKER_BUILD_ARGS: ""
  DOCKERHUB_USERNAME: xedriq
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:

  build_and_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract Git Tag Name
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
        build-args: ${{ env.DOCKER_BUILD_ARGS }}

  update_manifest:

    runs-on: ubuntu-latest
    needs: build_and_push_image

    steps:
    - name: Checkout manifest repo
      uses: actions/checkout@v4
      with:
        repository: 'xedriq/test-gitops-manifest'
        path: 'test-gitops-manifest'

    - name: Extract Git Tag Name
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Replace tag
      env:
        TAG: ${{ env.TAG_NAME }}
      run: |
        sed -i "s/tag:.*/tag: ${TAG}/g" my-app/values.yaml
      working-directory: test-gitops-manifest

    - name: Cat values
      run: cat my-app/values.yaml
      working-directory: test-gitops-manifest
    
    - name: Commit changes
      working-directory: test-gitops-manifest
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add my-app/values.yaml
        git commit -m "update image tag"
        
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push