name: Docker Image CI

on:
  push:
    tags:
    - 'v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'

env:
  IMAGE_NAME: my-app
  # DOCKERFILE_PATH: ./Dockerfile
  # DOCKER_BUILD_ARGS: ""
  DOCKERHUB_USERNAME: xedriq
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:

  build_and_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract Git Tag Name
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
        build-args: ${{ env.DOCKER_BUILD_ARGS }}

  update_manifest:

    runs-on: ubuntu-latest
    needs: build_and_push_image

    steps:
    - name: Setup ssh
      run: |
        # Create .ssh directory
        mkdir -p ~/.ssh
        # Add your existing private SSH key from secrets
        echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        # Set permissions for the private key
        chmod 600 ~/.ssh/id_rsa
        # Add GitHub to known hosts to prevent prompt
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout manifest repo
      uses: actions/checkout@v2
      with:
        repository: 'xedriq/test-gitops-manifest'
        path: 'test-gitops-manifest'
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Extract Git Tag Name
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Replace tag
      env:
        TAG: ${{ env.TAG_NAME }}
      run: |
        sed -i "s/tag:.*/tag: ${TAG}/g" my-app/values.yaml
      working-directory: test-gitops-manifest

    - name: Cat values
      run: cat my-app/values.yaml
      working-directory: test-gitops-manifest
    
    - name: Commit changes
      working-directory: test-gitops-manifest
      run: |
        git remote -v
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add my-app/values.yaml
        git commit -m "update image tag"
        git push origin main

    